"""Shared paths and settings for the vibe sorter.

Defaults match the container layout (/app/...). Every path can be overridden
with an env var so the probe can also be run locally against the mounted
./app/data directory without touching the service.

Everything lands under data/vibe, which .gitignore already covers via
`app/data/*` — including the generated cookies file.
"""

import os

APP_ROOT = os.getenv("VIBE_APP_ROOT", "/app")
DATA_DIR = os.getenv("VIBE_DATA_DIR", os.path.join(APP_ROOT, "data", "vibe"))

LIBRARY_FILE = os.path.join(DATA_DIR, "library.json")
AUDIO_DIR = os.path.join(DATA_DIR, "audio")
EMBED_DIR = os.path.join(DATA_DIR, "embeddings")
REPORT_DIR = os.path.join(DATA_DIR, "reports")
COOKIES_FILE = os.path.join(DATA_DIR, "cookies.txt")

# Playlists the model should never learn from or route into. "Liked Music" is
# the unlabelled pool, not a class; the mixes are generated by YouTube.
EXCLUDED_TITLES = {
    "Liked Music",
    "Episodes for Later",
    "My Supermix",
    "Discover Mix",
    "New Release Mix",
    "Replay Mix",
}

# Title substrings (case-insensitive) for playlists to skip. Empty by default:
# a playlist name is not reliable evidence of what's in it ("20. UNSORTED TECH"
# is a house/tech vibe, not a staging bin), so exclusions are the user's call
# via --exclude rather than something inferred here.
DEFAULT_EXCLUDE_PATTERNS = ()

# A playlist with fewer than this many tracks can't be learned reliably.
MIN_TRACKS_PER_PLAYLIST = int(os.getenv("VIBE_MIN_TRACKS", "15"))

# Snippet taken from the middle of each track.
SNIPPET_SECONDS = int(os.getenv("VIBE_SNIPPET_SECONDS", "60"))

# What the embedding model consumes. discogs-effnet wants 16kHz mono, and the
# loader resamples to this regardless of what's on disk.
SAMPLE_RATE = 16000

# Rate for the handcrafted rhythm/energy features. essentia's
# RhythmExtractor2013 and friends are tuned for 44.1kHz; handing them 16kHz
# audio produces plausible-looking nonsense — the same track measured 85 BPM at
# 16kHz and 125 BPM at 44.1kHz. Resampling doesn't change duration, so this
# costs a re-analysis and no re-download.
ANALYSIS_RATE = 44100

# What's stored. Originally these were 16kHz mono WAVs — the embedder's input
# written straight to disk — which made previews sound dull: 16kHz caps
# everything above 8kHz, so cymbals and air are simply missing, and mono
# collapses the image. m4a at full rate in stereo is both nicer to listen to
# and *smaller* (roughly 1MB against 1.9MB), since the embedder can resample
# on load and doesn't need the file to match its input format.
SNIPPET_FORMAT = os.getenv("VIBE_SNIPPET_FORMAT", "m4a")
SNIPPET_BITRATE = os.getenv("VIBE_SNIPPET_BITRATE", "128k")

# Older caches are WAV; both are readable, so an existing cache stays valid.
SNIPPET_EXTENSIONS = ("m4a", "wav")

# Fixed so re-runs sample the same tracks and stay comparable.
RANDOM_SEED = 1312


def ensure_dirs():
    for d in (DATA_DIR, AUDIO_DIR, EMBED_DIR, REPORT_DIR):
        os.makedirs(d, exist_ok=True)
