"""Shared paths and settings for the vibe sorter.

Defaults match the container layout (/app/...). Every path can be overridden
with an env var so the probe can also be run locally against the mounted
./app/data directory without touching the service.

Everything lands under data/vibe, which .gitignore already covers via
`app/data/*` — including the generated cookies file.
"""

import os

APP_ROOT = os.getenv("VIBE_APP_ROOT", "/app")
DATA_DIR = os.getenv("VIBE_DATA_DIR", os.path.join(APP_ROOT, "data", "vibe"))

LIBRARY_FILE = os.path.join(DATA_DIR, "library.json")
AUDIO_DIR = os.path.join(DATA_DIR, "audio")
EMBED_DIR = os.path.join(DATA_DIR, "embeddings")
REPORT_DIR = os.path.join(DATA_DIR, "reports")
COOKIES_FILE = os.path.join(DATA_DIR, "cookies.txt")

# Playlists the model should never learn from or route into. "Liked Music" is
# the unlabelled pool, not a class; the mixes are generated by YouTube.
EXCLUDED_TITLES = {
    "Liked Music",
    "Episodes for Later",
    "My Supermix",
    "Discover Mix",
    "New Release Mix",
    "Replay Mix",
}

# A playlist with fewer than this many tracks can't be learned reliably.
MIN_TRACKS_PER_PLAYLIST = int(os.getenv("VIBE_MIN_TRACKS", "15"))

# Snippet taken from the middle of each track.
SNIPPET_SECONDS = int(os.getenv("VIBE_SNIPPET_SECONDS", "60"))
SAMPLE_RATE = 16000

# Fixed so re-runs sample the same tracks and stay comparable.
RANDOM_SEED = 1312


def ensure_dirs():
    for d in (DATA_DIR, AUDIO_DIR, EMBED_DIR, REPORT_DIR):
        os.makedirs(d, exist_ok=True)
